Added my css animations website
WeBeginners-Community/CSS.Effects-Designs pull request #244
Opened 2022-10-20 18:08 UTC by ilhamansari

# Description

CSS animations website with different animations effects made by using html and mostly css. 

Fixes:  #239 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] Are you hacktoberfest contributor?

![Screenshot (12)](https://user-images.githubusercontent.com/102286043/197024991-8591b7b6-1149-4dc0-87b7-45ee02093cae.png)
![Screenshot (13)](https://user-images.githubusercontent.com/102286043/197025001-5c488362-6c33-4d2a-8656-bfe7ea4af9e1.png)

2022-10-20 18:46 UTC, Sulagna-Dutta-Roy requested changes
Please make one folder here then add all the files

2022-10-20 19:38 UTC, Sulagna-Dutta-Roy requested changes
Add this project under 'Css Animations' and make a folder along with it. Check other contributions.

2022-10-21 09:15 UTC, ilhamansari commented
Did all the changes as mentioned . @Sulagna-Dutta-Roy

2022-10-22 15:58 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-22 15:58 UTC, merged