Title: Create a floating label text input #23
WeBeginners-Community/CSS.Effects-Designs pull request #268
Opened 2022-10-22 19:23 UTC by Krrishn07

# Description

Provide new and update float label text input animation using html and css

Fixes:  #(issue no.)

#23

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

# Checklist:

- [x ] I have made this from my own
- [x ] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://drive.google.com/drive/u/1/my-drive

2022-10-22 19:24 UTC, Krrishn07 commented
Thanks for providing me this chance. Please review and merge my request

2022-10-22 20:02 UTC, Sulagna-Dutta-Roy requested changes
Add this project into Css animations folder.

2022-10-23 07:24 UTC, Krrishn07 commented
@Sulagna-Dutta-Roy The changes has been made please review and merge request.

2022-10-27 19:00 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-27 19:00 UTC, merged