Bakery Website
WeBeginners-Community/CSS.Effects-Designs pull request #445
Opened 2023-01-25 15:48 UTC by S-ishita

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

![Screenshot from 2023-01-25 20-54-15](https://user-images.githubusercontent.com/104543751/214609277-52f5aacc-7446-4529-bbcb-02ae829ab1b4.png)
![Screenshot from 2023-01-25 20-53-55](https://user-images.githubusercontent.com/104543751/214609287-1b46e655-cff4-4728-ace4-bb5455ce5242.png)
![Screenshot from 2023-01-25 20-53-49](https://user-images.githubusercontent.com/104543751/214609309-eb7b7199-a115-4332-a676-7fccbd7fe02d.png)

2023-01-26 09:05 UTC, Sulagna-Dutta-Roy requested changes
Issue no ???

2023-01-26 09:07 UTC, S-ishita commented
Issue #413

2023-01-27 07:20 UTC, Sulagna-Dutta-Roy commented
But this Issue I've assigned you. Maybe he's working on this one.

2023-01-28 20:52 UTC, Sulagna-Dutta-Roy approved these changes

2023-01-28 20:52 UTC, merged