[Added] 2 CSS animations
WeBeginners-Community/CSS.Effects-Designs pull request #47
Opened 2022-10-02 08:01 UTC by Anikaaasingh

# Description

Added 2 CSS animations.
1. On Mouse Hover Menu animation.
2. Heart trail animation on mouse move.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-10-02 12:05 UTC, Sulagna-Dutta-Roy requested changes
Make separate branches for the PRs

2022-10-03 18:00 UTC, Sulagna-Dutta-Roy commented
Its same right now

2022-10-06 19:13 UTC, Anikaaasingh commented
@Sulagna-Dutta-Roy kindly merge this .I tried making another branch but is was making  a separate pull request  which you told to close

2022-10-07 20:59 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-30 14:16 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-30 14:16 UTC, merged