added Css-Loader in new directory
WeBeginners-Community/CSS.Effects-Designs pull request #48
Opened 2022-10-02 09:33 UTC by Eli4479

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-10-02 18:42 UTC, Sulagna-Dutta-Roy requested changes
kindly add this project like:

Css Loaders/Css Loaders 1/index.html

This can be a folder

2022-10-02 18:53 UTC, Eli4479 commented
> kindly add this project like:
> 
> Css Loaders/Css Loaders 1/index.html
> 
> This can be a folder

changed path as ordered

2022-10-03 02:47 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-03 18:00 UTC, merged

2022-10-03 18:01 UTC, Sulagna-Dutta-Roy commented
your Issue no ????