added side navbar
WeBeginners-Community/CSS.Effects-Designs pull request #56
Opened 2022-10-02 19:56 UTC by akshit5565

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-10-03 18:05 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-03 18:06 UTC, Sulagna-Dutta-Roy requested changes
kindly change the folder name as 'Side Navbar' 
no punctuations use please

2022-10-03 18:40 UTC, akshit5565 commented
@Sulagna-Dutta-Roy  should i make another PR after the changes??

2022-10-05 18:34 UTC, Sulagna-Dutta-Roy commented
sure you can but make sure you delete the fork after I merge this project

2022-10-07 19:45 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-07 19:45 UTC, merged