gooey-svg-effect animations
WeBeginners-Community/CSS.Effects-Designs pull request #565
Opened 2023-02-18 18:54 UTC by ashadmuneer

# Description
I contributing gooey-svg-effect animation which is fully implement in html & c++.

Fixes:  #541 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
link- https://gooey-svg-effect-animations.ashadmuneer.repl.co

2023-02-18 18:54 UTC, ashadmuneer commented
@Sulagna-Dutta-Roy  check it

2023-02-18 20:28 UTC, Sulagna-Dutta-Roy requested changes
Css Animations/Gooey SVG Effects/your codes
Please follow the above

2023-02-20 05:31 UTC, ashadmuneer commented
@Sulagna-Dutta-Roy  changes done check it

2023-02-20 06:45 UTC, Sulagna-Dutta-Roy approved these changes

2023-02-20 06:46 UTC, merged