Upgraded contribution guidelines making new contributors workflow easy
WeBeginners-Community/CSS.Effects-Designs pull request #6
Opened 2022-10-01 12:45 UTC by Aman-0604

# Description

Upgraded contribution guidelines making new contributors workflow easy. 
Finding such a useful contribution guidelines also increases doing `Star` your repository.

## Type of change

- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-10-01 12:47 UTC, Aman-0604 commented
@Sulagna-Dutta-Roy  please merge the pull request ! You will like the new contribution guidelines as it so user-friendly and provides right path to beginners.

2022-10-01 19:57 UTC, Sulagna-Dutta-Roy requested changes
Add this link into the last: 
![Contributors](https://contributors-img.web.app/image?repo=sulagna-dutta-roy/Css-design-projects)

2022-10-01 20:49 UTC, Aman-0604 commented
@Sulagna-Dutta-Roy this link  is already involved in the last. Check !

<img width="1437" alt="Screenshot 2022-10-02 at 2 19 02 AM" src="https://user-images.githubusercontent.com/96296951/193427795-6c82ff9b-c80a-48b3-9f19-ecdb66fef1ff.png">

2022-10-01 21:18 UTC, Sulagna-Dutta-Roy approved these changes

2022-10-02 07:38 UTC, amelia2802 approved these changes

2022-10-02 07:38 UTC, merged