Buy me a coffee landing page clone issue no. #669
WeBeginners-Community/CSS.Effects-Designs pull request #670
Opened 2023-07-08 14:12 UTC by Shu12388y

# Description
This project is a clone of a website that is by me a coffee. I have made this project using HTML, CSS Javascript.
This project consists of multiple route pages

Fixes:  #669

## Type of change

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

![Screenshot from 2023-07-04 21-26-36](https://github.com/WeBeginners-Community/CSS.Effects-Designs/assets/91714143/6a3c306b-4746-4093-a6b7-a4fa54b6a8aa)

@Sulagna-Dutta-Roy  can you review and merge this project

2023-07-08 20:51 UTC, Sulagna-Dutta-Roy requested changes
Remove the packages like json files.  
Format: Landing Pages/ Buy Me Coffee/ your files

2023-07-09 13:15 UTC, Shu12388y commented
@Sulagna-Dutta-Roy I have made the changes you have mentioned above

2023-07-09 13:16 UTC, Sulagna-Dutta-Roy approved these changes

2023-07-09 13:16 UTC, merged

2023-07-09 13:16 UTC, Sulagna-Dutta-Roy commented
Thank you for the contribution